### ISSUE TITLE
Bug with decrypt mode

### ISSUE THREAD

**Issue by lightballer** [genericsdevelopmentstudio/md5-crypt#4]
When I tried to use decrypt mode terminal freezed and even pushing CTRl+C didn't help

**Comment by Explodeus** [comment]
Just wait, it'll decrypt it

**Comment by yehorbk** [comment]
I'll check it. What message are you decrypting?

> When I tried to use decrypt mode terminal freezed and even pushing CTRl+C didn't help

**Comment by lightballer** [comment]
I encrypt Node.JS and got df6191fe3bc2ed6424829f625a76c62a

**Comment by Explodeus** [comment]
Ok, thx, I'll try

**Comment by Explodeus** [comment]
Decryption is more power needed process than encryption. Please, be patient and wait)

**Comment by lightballer** [comment]
I understand, but I already wait about 20 minutes...

**Comment by yehorbk** [comment]
Okay. MD5 - it's one-way encoder and does not have decoder. ReverseMd library uses brute force to decode the data. It's not a good solution so we will find another. But now, you need to wait n-time to decode it.
